name: Python Uppercase1

on:
  push:
    paths:
      - ".github/workflows/python-uppercase/"
      - "py_app/**"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check python version
        run: python -v

      - name: Display current directory
        run: pwd

      - name: List files in current directory
        run: ls -la

      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: List files
        run: ls -R
      
      - name: Install python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'
          
      - name: Check python version
        run: python -v


      - name: Install Python dependencies
        uses: py-actions/py-dependency-install@v4
        with:
          path: "py_app/requirements.txt"
          update-pip: "true"
      
      - name: run tests
        working-directory: py_app
        run: python -v

          
