name: Python Uppercase build

on:
  push:
    paths:
      -".github/workflows/python-uppercase-build.yml"
      - "py_app/**"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install python dependencies
        uses: py-actions/py-dependency-install@v4
        with:
          path: "py_app/requirements.txt"
          update-pip: "true"

      - name: Run tests
        working-directory: py_app
        run: pytest -v

  build:
    runs-on: windows-latest
    needs: test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install PyInstaller
        run: pip install pyinstaller

      - name: Build EXE file
        working-directory: py_app
        run: pyinstaller --onefile uppercase.py

      - name: List files after build
        run: ls -R

      - name: Save artifacts to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: uppercase-exe
          path: py_app/dist/uppercase.exe
        
